theme: jekyll-theme-hacker
title: DH2650 Game, Technoscourge - Rise of the Adaptive

author: David  ̊Asberg dasberg@kth.se,
Jesper Lidbaum jlidbaum@kth.se,
Zhongyue Wu zhongyue@kth.se,
Laila Arman lailaa@kth.se,
Wanqing Zhou wanqingz@kth.se,